<h1>  Numpy function </h1>

In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,3,4,5],[2,3,6,7]])
print(arr1)

[[1 3 4 5]
 [2 3 6 7]]


<h3> .shape and .dtype and other function source </h3>
<h6> these shows </h6>

In [3]:
arr1.ndim

2

In [4]:
arr1.shape

(2, 4)

In [6]:
arr1.shape()

TypeError: 'tuple' object is not callable

In [7]:
arr1.dtype

dtype('int32')

<h6>to know more about .dtype go to numpy official documentation ther are multiple dtype such as it32 int64 float64 it dermined by compalier  or defied by us depend on how big or type of number like integer fraction </h6>

<h2>Defining array data type </h2>
<h6> we need to define array datatpye carefully </h6>
<h6> we can define datatype of array by extra dtpye= 'xxx' argumment after comma(,)</h6>

In [8]:
arr2 = np.array([2,4,5,7])
arr2.dtype

dtype('int32')

In [9]:
arr3 = np.array([2,4,9.5,4,6])
arr3.dtype

dtype('float64')

In [10]:
arr4 = np.array([2.9, 9.7, 5, 2], dtype= 'int32')
print(arr4)

[2 9 5 2]


In [11]:
arr5 = np.array([5,6,9,7], dtype = 'float64')
print(arr5)

[5. 6. 9. 7.]


In [12]:
arr6 = np.array([54454554545555, 2], dtype = 'int32')
print(arr6)

OverflowError: Python int too large to convert to C long

In [13]:
arr7 = np.array([54454554545555, 2], dtype = 'int64')
print(arr7)

[54454554545555              2]


In [14]:
arr8 = np.array([5445455454145555, 2], dtype = 'float64')
print(arr8)

[5.44545545e+15 2.00000000e+00]


<h2> numpy Arthematic </h2>

In [15]:
a = np.array([[1,5,7],[8,9,6]])
b = np.array([[9,4,5],[2,9,7]], dtype= 'float64')
c = np.array([[2,5,6],[8,8,3.6]])
d = np.array([[[9,4,5],[2,9,7]], [[2,5,6],[8,8,3.6]]])
e = np.array([5,6,56])
f = np.array([6,5,6,8,5])
g = np.array([5])


In [16]:
ab = a+b
print(ab.dtype)
print(f"{a+b}")

float64
[[10.  9. 12.]
 [10. 18. 13.]]


In [17]:
ac = a + c
print(ac.dtype)
print(ac)

float64
[[ 3.  10.  13. ]
 [16.  17.   9.6]]


In [18]:
ad = a + d
print(ad)

[[[10.   9.  12. ]
  [10.  18.  13. ]]

 [[ 3.  10.  13. ]
  [16.  17.   9.6]]]


In [19]:
print(d.shape)

(2, 2, 3)


In [20]:
adm = a * d
print(adm)

[[[ 9.  20.  35. ]
  [16.  81.  42. ]]

 [[ 2.  25.  42. ]
  [64.  72.  21.6]]]


In [21]:
ae = a + e
print(ae)

[[ 6 11 63]
 [13 15 62]]


In [22]:
ea = e + a
print(ea)

[[ 6 11 63]
 [13 15 62]]


In [23]:
af = a + f
print(af)

ValueError: operands could not be broadcast together with shapes (2,3) (5,) 

In [24]:
ag = a + g
print(ag)

[[ 6 10 12]
 [13 14 11]]


<h6> if each array projection cover each other fully in either way they can be oprated </h6>

<h2> Slicing </h2>

In [25]:
s1 = np.array([4,7,3,2,5])

In [26]:
i = s1[2:7]
print(i)

[3 2 5]


In [27]:
i[0]= 9
print(i)
print(s1)

[9 2 5]
[4 7 9 2 5]


<h6> ching value of array slice will achange value of array as well because C points a location to avoid this use .copy() method</h6>

<h4> .copy method </h4>

In [28]:
s2 = np.array([4,5,7,2,5])
i1 = s2[2:4]
print(i1)

[7 2]


In [29]:
i2 = s2[2:5].copy()
print(i2)

[7 2 5]


In [30]:
i2[0] = 45
print(i2)
print(s2)

[45  2  5]
[4 5 7 2 5]


In [31]:
s3 = np.array([[2,5,6],[9,6,7]])
print(s3)

[[2 5 6]
 [9 6 7]]


In [32]:
j = s3[1]
print(j)

[9 6 7]


In [33]:
j1 = s3[1,2]
print(j1)

7


In [34]:
j2 = s3[0:2]
print(j2)

[[2 5 6]
 [9 6 7]]


<h2> Reshape array </h2>

In [35]:
arr1 = np.arange(15)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [36]:
arr1.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
arr1.reshape(3,3)

ValueError: cannot reshape array of size 15 into shape (3,3)

In [38]:
arr1.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])