In [2]:
import numpy as np

<h1>Array builing</h1>

<h6> 1D array </h6>

In [2]:
d1 = np.array([5,5,48,4,4,])
print(d1)

[ 5  5 48  4  4]


In [3]:
np.array([2,3,4,55,4])

array([ 2,  3,  4, 55,  4])

<h6> 2d array </h6>

In [3]:
d2 = np.array([[1,32,45],[3,4,5.5]])
print(d2)

[[ 1.  32.  45. ]
 [ 3.   4.   5.5]]


In [4]:
d2_int = np.array([[1,2,3,5],[5,3,6,2],[6,3,7,9]])
print(d2_int)

[[1 2 3 5]
 [5 3 6 2]
 [6 3 7 9]]


<h6>3d array</h6>

In [6]:
d3 = np.array([[[2,6,4,6],[4,6,8,7]],[[2,6,7,6],[8,6,3,7]]])
print(d3)

[[[2 6 4 6]
  [4 6 8 7]]

 [[2 6 7 6]
  [8 6 3 7]]]


<h6> 4D array </h6>

In [7]:
d4 = np.array([[[[2,6,4,6],[4,6,8,7]],[[2,6,7,6],[8,6,3,7]]],[[[2,6,4,6],[4,6,8,7]],[[2,6,7,6],[8,6,3,7]]]])
print(d4)

[[[[2 6 4 6]
   [4 6 8 7]]

  [[2 6 7 6]
   [8 6 3 7]]]


 [[[2 6 4 6]
   [4 6 8 7]]

  [[2 6 7 6]
   [8 6 3 7]]]]


<h6> Rubic Cube Array </h6> assign value by layerwise

In [8]:
rubic1 = np.array([[[1,1,1],[2,2,2],[3,3,3]],[[1,1,1],[2,0,2],[3,3,3]],[[1,1,1],[2,2,2],[3,3,3]]])
print(rubic1)

[[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[1 1 1]
  [2 0 2]
  [3 3 3]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]]]


<h6> making array with .arange function </h6>

In [9]:
a1 = np.arange(5)
print(a1)

[0 1 2 3 4]


In [10]:
a2 = np.arange(5,4)
print(a2)

[]


<h3> making empty array </h3>

<h6>1D empty array</h6>

<h6>using np.zeros ,  np.ones and np.empty </h6>

In [11]:
e1 = np.zeros(9)
print(e1)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
e1.dtype

dtype('float64')

In [13]:
print(e1.dtype)

float64


<h6>2d empty array</h6>

In [14]:
e2 = np.zeros((5,4))
print(e2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


<h6> 3d empty array </h6>

In [15]:
e3 = np.zeros((5,4,3))
print(e3)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [16]:
r5c7l3 = np.zeros((3,5,7))
print(r5c7l3)

[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]


<h6> using np.ones and np.empty </h6>

In [17]:
ones_array = np.ones((5,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
empty_array = np.empty((5,2))
print(empty_array)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.42418987e-306]
 [1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306]
 [1.29061142e-306 5.53353523e-322]]


In [19]:
empty_array2 = np.empty((4,1))
print(empty_array2)

[[1.16157062e-311]
 [1.16156964e-311]
 [1.16156964e-311]
 [1.16156964e-311]]


In [20]:
empty_array3 = np.empty((3,2,1))
print(empty_array3)

[[[ 1. ]
  [32. ]]

 [[45. ]
  [ 3. ]]

 [[ 4. ]
  [ 5.5]]]


<h6> np.zeros and np.empty are not same in np.zeros value of each element must be zero but in np.empty it could be garbadge value </h6>

<h2> Speed Test Numpy vs Python</h2>
<h6> numpy is almost 100 to 1000 times faster then python because it is written in C language and C communicate with mamory directtly wheather python is interpreted language </h6>

In [21]:
x = list(range(5))
print(x)

[0, 1, 2, 3, 4]


In [22]:
list = list(range(100000))
array = np.arange(100000)

In [23]:
%timeit list1 = [i*3 for i in list]

3.79 ms ± 200 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [25]:
%timeit array1 = array*3

52.4 µs ± 59.6 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [26]:
(3*10**-3)/(53*10**-6)

56.60377358490566