In [1]:
import pandas as pd
import numpy as np

In [3]:
series =  np.arange(18).reshape(6,3)
print(series)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [6]:
df = pd.DataFrame(series, columns = ['A', 'B', 'C'])
print(df)

    A   B   C
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14
5  15  16  17


In [7]:
df.to_csv('writedInCSV.csv')

In [8]:
df.to_csv('fileWithoutIndex.csv', index = False)